version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      patch:
        update-types:
          - patch
  - package-ecosystem: docker
    directories: 
      - /
      - .devcontainer/
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - minor
          - patch
