name: Code

on:
  push:
  pull_request:

jobs:
  lint:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.2.1

      - name: Install Stable Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.5

      - name: Check Formatting
        run: >
          cargo fmt
          --all
          --check

      - name: Lint with Clippy
        run: >
          cargo clippy
          --all-targets
          --all-features
          --no-deps
          --
          --deny warnings

  test:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.2.1

      - name: Install stable Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.5

      - name: Run Tests
        run: >
          cargo test
          --all-targets
          --all-features
